### PR TITLE
matthlee - cartesian chart margin fixes

### PR DESCRIPTION
**Pull request by MatthLee**
Fixing left, right, and bottom margins, negotiating x-label overflow with y-axis label widths, fixing 3 related bugs.

[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/44)

### CODE REVIEW

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 159 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxH5Fya9oKHU7AAbQTZ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L159)):</sup>
*comment?*

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 159 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxH5Fya9oKHU7AAbQTZ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L159)):</sup>
not resolved!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
nice review...

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 409 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxRkIj_3P8wXuTPr4Ou)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L409)):</sup>
nit: whitespace

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 374 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxRkCk_c1LRSsNVbM2j)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L374)):</sup>
nit: whitespace

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 377 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxRkT_kv2Wdkn6jVXXU)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L377)):</sup>
I think it'd be really helpful to have a quick meeting for explaining this or adding some comments here. Tricky to wrap my head around all the concepts going on in this method.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1415 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxRl4jV9A_VTUTY1CPr)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1415)):</sup>
We want a negative tick width here? A comment would be helpful here. Reading the d3 documentation doesn't seem like a negative is special?
https://github.com/mbostock/d3/wiki/SVG-Axes#tickSize

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1120 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxRlXzIEUEr9dCQkOlv)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1120)):</sup>
nit: whitespace

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 427 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX97tY0HDNGqnB3hkW)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L427)):</sup>
Does renderYAxes control both axes? Seems like it only controls the Y1 axis, if so we should call it renderY1Axis.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 428 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX9HlwZflCbkwixffk)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L428)):</sup>
Feel free to change these to for..of loops.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 449 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX9gplWZnf0fVI35J9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L449)):</sup>
size is confusing, is this width?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 449 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX9gplWZnf0fVI35J9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L449)):</sup>
Maybe something like xWidth...

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 449 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX9gplWZnf0fVI35J9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L449)):</sup>
Maybe something like xWidth...

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 409 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXAdWm_wIFjx5hib4c)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L409)):</sup>
labelOffset should probably just take the outer padding into account.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 456 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXAz0hEbfNKGRROMTt)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L456)):</sup>
This is not used outside the ifs, declare it inside.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 386 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXBbZvnG-XrBx-QuAs)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L386)):</sup>
Could also rename showOnRight -> showY2OnRight

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 408 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXD3ZLhkGcxN-Yr3ql)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L408)):</sup>
Just name it bottomMargin?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 478 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXDA0nhdUTkjqFB34k)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L478)):</sup>
Is the ceil necessary?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 407 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXDI28y3lwez-1kbwg)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L407)):</sup>
Consider naming these something like y2Width rather than max, max vs. limit is a bit confusing.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 974 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXDza2DPJok3FudSSe)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L974)):</sup>
Consider renaming these: shouldRenderY2Axis, shouldRenderXAxis, etc.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 974 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXDza2DPJok3FudSSe)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L974)):</sup>
Nevermind about shouldRenderXAxis, I see it is used for both x and y1. 
Can we just get rid of this one and use shouldRenderAxis(y2, "secShow")? It does some extra checks, but better than having two slightly different methods I think.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by MatthLee** [comment]
Review status: 0 of 8 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/PowerBIVisualsTests/visuals/columnChartTests.ts, line 3544 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxIasI1vJXxnPv0cygq)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/PowerBIVisualsTests/visuals/columnChartTests.ts#L3544)):</sup>
I should really turn some of these exact checks into "between" checks to allow for some minor design changes or adjustments.

---

<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1463 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX2Nu_nGW83MK4tN4v)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1463)):</sup>
Do this now!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1130 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXy8ZPI8Peu6NdqESX)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1130)):</sup>
So calculate the axes 3 times potentially?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1130 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXy8ZPI8Peu6NdqESX)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1130)):</sup>
And aren't the margins and everything going to be out of sync after the last time you calculateAxes?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by jcludwig** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by vijanu** [comment]
Reviewed 1 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 21 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1090 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxbJYbOAkYLSf8LDJ8b)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1090)):</sup>
(minor) remove "is" here

---

<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 415 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxbOaqohfbsj1iyTOJZ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L415)):</sup>
can we use != null to account for undefined/null values

---

<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 428 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX9HlwZflCbkwixffk)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L428)):</sup>
+1 to update to for...of

---

<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 443 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxbOvA-wDsG2hYKZCIF)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L443)):</sup>
update to for...of

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by vijanu** [comment]
Reviewed 5 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 21 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
Really do not like how Reviewable spams the comment thread here...

**Comment by spatney** [comment]
True, though it only really posts once you hit publish. Trick is to input all review comments before hitting publish. It will maintain your comments between sessions even if you don't publish.

**Comment by magus** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 449 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX9gplWZnf0fVI35J9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L449)):</sup>
Just 'acknowledged' this becaues I thought it was like a :+1: but it may have collapsed the comments.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 478 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXDA0nhdUTkjqFB34k)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L478)):</sup>
I think it is but maybe we should just ceil the rotated height calculation or the xMax earlier for clarity. I think if we change our SVGHeight calculations to return the decimal values (getBoundingClientRect instead of getBBox) we may start getting decimal heights.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
Reviewed 1 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 20 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by magus** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 20 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by davsets** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 20 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 449 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX9gplWZnf0fVI35J9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L449)):</sup>
Oops, wanted to +1 not say it's good.  width would be much better than size (the fact that it's x dimension should be implied when saying "width" I feel)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by MatthLee** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

<sup>**[src/Clients/PowerBIVisualsTests/visuals/columnChartTests.ts, line 3544 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxIasI1vJXxnPv0cygq)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/PowerBIVisualsTests/visuals/columnChartTests.ts#L3544)):</sup>
Akvelon fixed this since there is slight variation on Macs also.

---

<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1130 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXy8ZPI8Peu6NdqESX)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1130)):</sup>
yes, potentially. it should be in sync the last time, as calculateAxes takes in the stabilized margins.

---

<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 478 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXDA0nhdUTkjqFB34k)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L478)):</sup>
it is required for a check later on that we hit a margin limit (and need ellipsis)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Comment by MatthLee** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1415 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxRl4jV9A_VTUTY1CPr)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1415)):</sup>
yes, negative tickSize allows us to draw gridlines without having to invert the translate for the axis itself

---

<sup>**[src/Clients/Visuals/cartesian/cartesianChart.ts, line 1463 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX2Nu_nGW83MK4tN4v)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/cartesian/cartesianChart.ts#L1463)):</sup>
Done.

---

<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 407 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxXDI28y3lwez-1kbwg)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L407)):</sup>
Done.

---

<sup>**[src/Clients/Visuals/common/axisHelper.ts, line 449 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44#-JxX9gplWZnf0fVI35J9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/99a50586f5c452380eb0502a5b6bab5d4bb05c96/src/Clients/Visuals/common/axisHelper.ts#L449)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/44)

**Pull request merged**
