### PR TITLE
Chiclet Slicer visual

### PR DESCRIPTION
**Pull request by uve**
screen shot on 2015-10-16 at 20-54-12

[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/128)

### CODE REVIEW

**Comment by jcludwig** [comment]
Reviewed 4 of 13 files at r1.
Review status: 4 of 13 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/_references.ts, line 44 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11hwBjJ0gYyOsz4Xjz)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/PowerBIVisualsPlayground/_references.ts#L44)):</sup>
Up one, to keep sorted.


---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleSlicerXData.ts, line 73 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11ivETK6mDZZPmFDxb)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleSlicerXData.ts#L73)):</sup>
Pick a different queryName.


---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleSlicerXData.ts, line 81 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11iyx1ld4_zJXMCQY8)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleSlicerXData.ts#L81)):</sup>
Roles?


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 42 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11jd55RQoeD9yurZEx)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L42)):</sup>
data.createDisplayNameGetter('Role_DisplayName_Values')


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 46 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11jXUOEnkbDb6TfEnc)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L46)):</sup>
Why GroupingOrMeasure?


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 63 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11jlwevswA5oCBgove)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L63)):</sup>
Remove this. Sort order is handler at the visual container level.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 67 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11k5cqXVB71UuE-ULY)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L67)):</sup>
Please put this in an object sibling to "general":
selection: {
                displayName: data.createDisplayNameGetter('Visual_SelectionControls'),
                properties: {
                    selectAllCheckboxEnabled: {
                        displayName: data.createDisplayNameGetter('Visual_SelectAll'),
                        type: { bool: true }
                    },
                },
            }


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 71 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11kIBb_P9-FtO8qLbK)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L71)):</sup>
showDisabled, use camel-case for object/property names.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 100 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11kYelDIW539MaU5Ps)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L100)):</sup>
This is handled elsewhere, you should be able to remove this.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 120 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11lMANPCw_mYUltWrn)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L120)):</sup>
I think we should put outlineColor and outlineWeight in general to be consistent with the existing slicer. I don't think we need to be able to control these independently...


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 145 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11m1SwDDugnLP4AucV)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L145)):</sup>
I don't think we need per-row width and height...


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 170 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11mTDRZSIK08qpO4Wr)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L170)):</sup>
Visual_outlineColor


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 176 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11mDIPOs282141iskX)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L176)):</sup>
outlineColor and outlineWeight can come from general.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 200 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11mjeW_ePNMff4B5oG)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L200)):</sup>
This rule appears to be more strict than the one below, I don't think this does anything.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 217 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11n0ddB1aeeVq66bPi)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L217)):</sup>
I think this should be true, right?


---

<sup>**[src/Clients/Visuals/visuals/samples/slicerX.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11nILYBCqB9jVHqD92)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/visuals/samples/slicerX.ts#L31)):</sup>
For now, please just use the literal construction syntax rather than this helper method.


---

<sup>**[src/Clients/Visuals/visuals/samples/slicerXConverter.ts, line 1 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K134A5I4dM4ncTkeHVa)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/visuals/samples/slicerXConverter.ts#L1)):</sup>
Merge this into the slicerX.ts file for now.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128)

**Comment by jcludwig** [comment]
I need a bit more time to understand the requirements and some of the data view mapping implications.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128)

**Comment by uve** [comment]
Review status: 0 of 9 files reviewed at latest revision, 16 unresolved discussions.

---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 42 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11jd55RQoeD9yurZEx)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L42)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 46 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11jXUOEnkbDb6TfEnc)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L46)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 63 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11jlwevswA5oCBgove)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L63)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 71 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11kIBb_P9-FtO8qLbK)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L71)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 217 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11n0ddB1aeeVq66bPi)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L217)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128)

**Comment by uve** [comment]
Review status: 0 of 9 files reviewed at latest revision, 16 unresolved discussions.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/CarLogosData.ts, line 81 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11iyx1ld4_zJXMCQY8)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/PowerBIVisualsPlayground/sampleDataViews/CarLogosData.ts#L81)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts, line 170 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11mTDRZSIK08qpO4Wr)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/capabilities/samples/slicerX.capabilities.ts#L170)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/slicerX.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K11nILYBCqB9jVHqD92)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/visuals/samples/slicerX.ts#L31)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/slicerXConverter.ts, line 1 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128#-K134A5I4dM4ncTkeHVa)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/29de663b943b62e83fbcf8a5cf519ca5bab2486c/src/Clients/Visuals/visuals/samples/slicerXConverter.ts#L1)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/128)

**Pull request merged**
