### PR TITLE
Add a new Word Cloud visual.

### PR DESCRIPTION
**Pull request by IgnatVilesov**
[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/135)

### CODE REVIEW

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/wordCloud.ts, line 146 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HhZ-xeVeEBfjSEWOx)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/wordCloud.ts#L146)):</sup>
This is not a valid data view mapping. Since I think we need to do word-breaking client side you should just use a table:

 table: {
                rows: {
                    for: { in: 'Values' },
                    dataReductionAlgorithm: { window: {} }
                }
}


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/wordCloud.ts, line 211 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HiLA1D3X6Qk4T4tU2)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/wordCloud.ts#L211)):</sup>
This almost certainly doesn't need to be a member variable. Take a look at the AreaRangeChart to see how I organized the update->converter->render flow.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/wordCloud.ts, line 465 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HiljBkTwknHaeM4lW)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/wordCloud.ts#L465)):</sup>
If this stuff is copied from somewhere you need to include attribution to the original author.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/wordCloud.ts, line 146 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HhZ-xeVeEBfjSEWOx)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/wordCloud.ts#L146)):</sup>
Actually if we add a role for frequency as well we'll have to do something like (untested):

table: {
    rows: { select: [ { bind: { to: 'Value' } }, { bind: { to: 'Frequency' } } ] }
}


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleCountriesData.ts, line 147 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HlgcbnEYfmv-tZoxz)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleCountriesData.ts#L147)):</sup>
Let's make sure we add roles for all column metadata.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/wordCloud.ts, line 32 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1Hm6JvRkHY5Znp2rLI)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/wordCloud.ts#L32)):</sup>
I wouldn't bother with this, you can just use D3.Selection


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/wordCloud.ts, line 146 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HhZ-xeVeEBfjSEWOx)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/wordCloud.ts#L146)):</sup>
Sorry, this won't work as it, I need to think about this a bit...


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by IgnatVilesov** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 32 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1Hm6JvRkHY5Znp2rLI)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/samples/wordCloud.ts#L32)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 146 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HhZ-xeVeEBfjSEWOx)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/samples/wordCloud.ts#L146)):</sup>
This should work. We'll also need another role here for the frequency, that can go in the values part of categorical.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 1 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1L9STU7l35LZsaN456)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/df72fe679f196848ed8eeb5d75e60dad2d64c35a/src/Clients/Visuals/visuals/samples/wordCloud.ts#L1)):</sup>
If the wordcloud layout algorithm was copied from somewhere we need to attribute it to the original author.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
Reviewed 6 of 9 files at r1.
Review status: 3 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by IgnatVilesov** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleCountriesData.ts, line 147 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HlgcbnEYfmv-tZoxz)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleCountriesData.ts#L147)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 146 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HhZ-xeVeEBfjSEWOx)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/samples/wordCloud.ts#L146)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleCountriesData.ts, line 166 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1MaOpl8oTEE844fYA8)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9b7040100de86c9c41796c384ea7038403e7be07/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleCountriesData.ts#L166)):</sup>
Shouldn't need the table data view, the categorical should be sufficient.


---

<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 345 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1MaaO9fU7Yv1fmGNO5)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9b7040100de86c9c41796c384ea7038403e7be07/src/Clients/Visuals/visuals/samples/wordCloud.ts#L345)):</sup>
If you need a table view you need to declare the data view mappings for one. I am surprised this is necessary you should be able to just use the categorical.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 345 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1MaaO9fU7Yv1fmGNO5)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9b7040100de86c9c41796c384ea7038403e7be07/src/Clients/Visuals/visuals/samples/wordCloud.ts#L345)):</sup>
Fixed this for you.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/PowerBIVisualsTests/helpers/performanceTestsHelpers.ts, line 557 \[r5\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1R42IlttANAeQY5iuZ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/b6877a401c914828082bb4c2ce7f06aeeeca8101/src/Clients/PowerBIVisualsTests/helpers/performanceTestsHelpers.ts#L557)):</sup>
Feel free to just omit wordcloud from the perf tests.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by jcludwig** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by IgnatVilesov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleCountriesData.ts, line 166 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1MaOpl8oTEE844fYA8)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9b7040100de86c9c41796c384ea7038403e7be07/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleCountriesData.ts#L166)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 345 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1MaaO9fU7Yv1fmGNO5)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9b7040100de86c9c41796c384ea7038403e7be07/src/Clients/Visuals/visuals/samples/wordCloud.ts#L345)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by IgnatVilesov** [comment]
Review status: 7 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 211 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HiLA1D3X6Qk4T4tU2)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/samples/wordCloud.ts#L211)):</sup>
Done.


---

<sup>**[src/Clients/PowerBIVisualsTests/helpers/performanceTestsHelpers.ts, line 557 \[r5\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1R42IlttANAeQY5iuZ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/b6877a401c914828082bb4c2ce7f06aeeeca8101/src/Clients/PowerBIVisualsTests/helpers/performanceTestsHelpers.ts#L557)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by IgnatVilesov** [comment]
Review status: 7 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/Visuals/visuals/samples/wordCloud.ts, line 465 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135#-K1HiljBkTwknHaeM4lW)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/2f4ac9bb68632792b4ed755ed8c12d27f22f0ab3/src/Clients/Visuals/visuals/samples/wordCloud.ts#L465)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/135)

**Comment by v-kazaki** [comment]
Do not merge for now.

**Comment by v-kazaki** [comment]
Looks good.

**Comment by dmitriy-tarasov** [comment]
Reviewed, looks good.

**Pull request merged**
