### PR TITLE
Dev/v grniki/radar chart

### PR DESCRIPTION
**Pull request by uve**
Created a new RadarChart visual.
screen shot 2015-09-26 at 02 53 16

[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/115)

### CODE REVIEW

**Comment by spatney** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 140 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-JqcXyujT-AcTzh4SU)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L140)):</sup>
are these constants? use static, and use PascalCasing


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 181 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-Jqp3LxWEtCXYZqo5D)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L181)):</sup>
remove if not needed


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 201 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-JquMLaW3WJWGYoPyG)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L201)):</sup>
should this margin be a constant?


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 290 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-Jr1vAYGOg3s7owgo9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L290)):</sup>
these styles should be added to the .less file instead of hardcoding them 


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 316 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-Jr9yqg-P76iN0_Aak)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L316)):</sup>
same with these styles.. move them to the .less file


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 396 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-JrG9dh62nM3O3WU7q)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L396)):</sup>
make this duration stataic


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115)

**Comment by MatthLee** [comment]
Review status: 0 of 9 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 94 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-K4cYxLKHOfsMeXym2)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L94)):</sup>
nit: two consecutive blank lines not allowed by TSLINT 


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 165 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-K4LjyeMmiIrn8vEqW)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L165)):</sup>
return type


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 368 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-KhS5tkmHqGvGIf-DU)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L368)):</sup>
we should be able to write this using D3 data binding and avoid the forEach and indexed classes. let me know if you need help.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 391 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-KfqzsY8fr4cIVsAwW)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L391)):</sup>
we shouldn't need to index a class like this...


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 392 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-KfZ_LAFfgULwL4MNo)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L392)):</sup>
please attach events on enter(), not to the update selection.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115)

**Comment by uve** [comment]
Review status: 0 of 10 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 108 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-K4cYxLKHOfsMeXym2)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L108)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 166 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-JqcXyujT-AcTzh4SU)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L166)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 220 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-K4LjyeMmiIrn8vEqW)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L220)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 227 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-Jqp3LxWEtCXYZqo5D)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L227)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 241 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-JquMLaW3WJWGYoPyG)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L241)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 336 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-Jr1vAYGOg3s7owgo9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L336)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 359 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-Jr9yqg-P76iN0_Aak)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L359)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 405 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-KhS5tkmHqGvGIf-DU)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L405)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 443 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-KfqzsY8fr4cIVsAwW)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L443)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 444 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-KfZ_LAFfgULwL4MNo)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L444)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 447 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-JrG9dh62nM3O3WU7q)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/8a6af4a15fe891dd482e507c2db689061b2b7c43/src/Clients/Visuals/visuals/radarChart.ts#L447)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115)

**Comment by MatthLee** [comment]
Reviewed 6 of 9 files at r1, 3 of 4 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115)

**Comment by MatthLee** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/radarChart.ts, line 368 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115#-K-o-Hvklz-3tIMYe83w)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/09c7961ef400c9c7a9b1c1d8412504050d176fd3/src/Clients/Visuals/visuals/radarChart.ts#L368)):</sup>
create a formatter like this (just an example from scatter):

                let formatter = valueFormatter.create({
                    format: valueFormatter.getFormatString(keySourceColumn, scatterChartProps.general.formatString),
                    value: dataView.matrix.rows.root.children[0],
                    value2: dataView.matrix.rows.root.children[rowChildrenLength-1],
                });

then:
text( item => formatter.format(item))


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/115)

**Pull request merged**
