### PR TITLE
Added new dotPlot visual

### PR DESCRIPTION
**Pull request by uve**
Created a new dotPlot visual.
screen shot 2015-10-05 at 16 42 54

[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/119)

### CODE REVIEW

**Comment by MatthLee** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 295 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K-yBGX00wTQ0hUNVkd0)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/64fa10f4ac25a74ed8b0a05fe7aaffb078caa509/src/Clients/Visuals/visuals/samples/dotPlot.ts#L295)):</sup>
'dots' variable is not necessary. Just use the 'selection' variable from above.
typical flow is:
let selection = someElement.selectAll(selector).data(viewModel);
selection.enter().append('shape').classed('shapeClass');
selection.attr(... position and style ..);
selection.exit().remove();


---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 322 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K-yBjn2S0kVTwe9MSSm)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/64fa10f4ac25a74ed8b0a05fe7aaffb078caa509/src/Clients/Visuals/visuals/samples/dotPlot.ts#L322)):</sup>
backquotes not necessary, just use SVGUtil.translate() like:
.attr('transform', SVGUtil.translate(0, translateY))


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119)

**Comment by MatthLee** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 191 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K-yCEK2D4scN4pRipi5)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/64fa10f4ac25a74ed8b0a05fe7aaffb078caa509/src/Clients/Visuals/visuals/samples/dotPlot.ts#L191)):</sup>
please with with Ignat to add tooltipInfo to each dataPoint, and then set the tooltipManager callback at the end of your render function.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119)

**Comment by uve** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 191 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K-yCEK2D4scN4pRipi5)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/64fa10f4ac25a74ed8b0a05fe7aaffb078caa509/src/Clients/Visuals/visuals/samples/dotPlot.ts#L191)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 295 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K-yBGX00wTQ0hUNVkd0)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/64fa10f4ac25a74ed8b0a05fe7aaffb078caa509/src/Clients/Visuals/visuals/samples/dotPlot.ts#L295)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 322 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K-yBjn2S0kVTwe9MSSm)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/64fa10f4ac25a74ed8b0a05fe7aaffb078caa509/src/Clients/Visuals/visuals/samples/dotPlot.ts#L322)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119)

**Comment by MatthLee** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119)

**Comment by MatthLee** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 60 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K0HqkpGgNAPm23SVKZX)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/348daacd90416645432805e14d27f2bccbdbfe1f/src/Clients/Visuals/visuals/samples/dotPlot.ts#L60)):</sup>
this doesn't work in the product - please look at how Histogram uses capabilities. You need use a single bucket and map to categories in order to get an array of all the values.

            dataRoles: [{
                name: "Y",
                kind: VisualDataRoleKind.GroupingOrMeasure,
                displayName: data.createDisplayNameGetter("Role_DisplayName_Value")
            }],
            dataViewMappings: [{
                conditions: [
                    { 'Y': { min: 1, max: 1 } },
                ],
                categorical: {
                    categories: {
                   	    bind: { to: "Y" }
                    }
                }
            }],

And then just update your converter to look at dataView.categorical.categories.values instead of values.values


---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 323 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K0HrgUGzCAmNrAWjtPG)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/348daacd90416645432805e14d27f2bccbdbfe1f/src/Clients/Visuals/visuals/samples/dotPlot.ts#L323)):</sup>
please also create a valueFormatter and add .tickFormat( to the end of this axis chain.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119)

**Comment by MatthLee** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/samples/dotPlot.ts, line 323 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119#-K0HrgUGzCAmNrAWjtPG)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/348daacd90416645432805e14d27f2bccbdbfe1f/src/Clients/Visuals/visuals/samples/dotPlot.ts#L323)):</sup>
See histogram.ts for an example


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/119)

**Pull request merged**
