### PR TITLE
Added a new AreaRangeChart visual

### PR DESCRIPTION
**Pull request by uve**
Added a new AreaRangeChart visual.
screen shot on 2015-10-13 at 02-07-28

[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/124)

### CODE REVIEW

**Comment by jcludwig** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleData.ts, line 44 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K126tjUbNqAUXllY1OQ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/PowerBIVisualsPlayground/sampleData.ts#L44)):</sup>
remove empty line


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 36 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K128kwvuL4iv6eWYKno)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L36)):</sup>
When do we ever pass in svg or margin?


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 68 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K127dukOmBqF34kJgII)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L68)):</sup>
Don't bother with "any" type.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 111 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K133AaPhzCrwokJKLEk)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L111)):</sup>
There's no way to get data in the form you have for the sample with data mappings like this (as far as I know). We really need to test these visuals in the product and not just construct sample data in the playground.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 124 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1285hfJ5YTmFfT35iV)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L124)):</sup>
dataPoint? Did you try this?


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 125 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K128BGZuCCN8Ma1Tdc_)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L125)):</sup>
data.createDisplayNameGetter('Visual_DataPoint'),


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 128 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K128FOfrRUfCAWxwywc)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L128)):</sup>
data.createDisplayNameGetter('Visual_Fill'),


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 171 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K128PMlJdcak2EReHYE)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L171)):</sup>
Use our palette.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 205 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K129SAJSrz9OSV2-W1W)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L205)):</sup>
Unfortunately we have to stick with "var" until our DevTools are updated.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 242 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K129FDOJSJHjCSFcUH2)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L242)):</sup>
We do these checks in converter(), that should be sufficient.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 250 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1291iuVQQDV48K8VfJ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L250)):</sup>
No need for Boolean() here.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 310 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K129KOjnSK19m9Y0vWl)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L310)):</sup>
Generally we just "return" which returns undefined.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by uve** [comment]
Review status: 6 of 8 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleData.ts, line 44 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K126tjUbNqAUXllY1OQ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/PowerBIVisualsPlayground/sampleData.ts#L44)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 36 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K128kwvuL4iv6eWYKno)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L36)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 68 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K127dukOmBqF34kJgII)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L68)):</sup>
without "any" it results in the following errors: 
error TS2339: Property 'fill' does not exist on type '{ general: { formatString: DataViewObjectPropertyIdentifier; }; dataPoint: { fill: DataViewObject...'.
error TS2339: Property 'formatString' does not exist on type '{ general: { formatString: DataViewObjectPropertyIdentifier; }; dataPoint: { fill: DataViewObject...'.
error TS2339: Property 'formatString' does not exist on type '{ general: { formatString: DataViewObjectPropertyIdentifier; }; dataPoint: { fill: DataViewObject...'.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 111 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K133AaPhzCrwokJKLEk)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L111)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 124 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1285hfJ5YTmFfT35iV)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L124)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 125 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K128BGZuCCN8Ma1Tdc_)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L125)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 128 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K128FOfrRUfCAWxwywc)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L128)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 171 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K128PMlJdcak2EReHYE)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L171)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 205 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K129SAJSrz9OSV2-W1W)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L205)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 242 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K129FDOJSJHjCSFcUH2)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L242)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 250 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1291iuVQQDV48K8VfJ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L250)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 310 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K129KOjnSK19m9Y0vWl)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L310)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 205 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K129SAJSrz9OSV2-W1W)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L205)):</sup>
Actually, maybe we just do the let->var conversion when we make the package...we can leave as let. Sorry for the flip-flop.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 76 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1AaKOEO_rqFP2oIKNo)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/289e437f76d7b2113c37ead7bdeddc30e9417e54/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L76)):</sup>
You can skip the series metadata, we're not actually using it here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/services/visualPluginService.ts, line 355 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1AaWJ5SmO3QCrTjAkT)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/289e437f76d7b2113c37ead7bdeddc30e9417e54/src/Clients/Visuals/services/visualPluginService.ts#L355)):</sup>
Just remember to remove this before merging ;)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by uve** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 76 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1AaKOEO_rqFP2oIKNo)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/289e437f76d7b2113c37ead7bdeddc30e9417e54/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L76)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/services/visualPluginService.ts, line 355 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1AaWJ5SmO3QCrTjAkT)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/289e437f76d7b2113c37ead7bdeddc30e9417e54/src/Clients/Visuals/services/visualPluginService.ts#L355)):</sup>
Sure.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 205 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K129SAJSrz9OSV2-W1W)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/db5142718fe6def405084744f95e9e428ac6effd/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L205)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by uve** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 76 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1AaKOEO_rqFP2oIKNo)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/289e437f76d7b2113c37ead7bdeddc30e9417e54/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L76)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 136 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1Avi8_8AGJOt9hpwET)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/c52901b761b426d0e110278c87d3052c0fc31b19/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L136)):</sup>
I think this call needs to be: 
createValueColumns(columns, [districtExpr], dataViewMetadata.columns[1])


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 562 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1AxkLBe-G6qRadlkoR)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/c52901b761b426d0e110278c87d3052c0fc31b19/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L562)):</sup>
Not sure if this is right, please double-check.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
Reviewed 1 of 8 files at r1, 1 of 2 files at r2, 4 of 4 files at r3.
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by uve** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 136 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1Avi8_8AGJOt9hpwET)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/c52901b761b426d0e110278c87d3052c0fc31b19/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L136)):</sup>
Changed, but there is no difference


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 562 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1AxkLBe-G6qRadlkoR)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/c52901b761b426d0e110278c87d3052c0fc31b19/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L562)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 463 \[r5\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1L5leKKh5RO5V_PH6i)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/5b15ae934d67771acf87eb672908460b6576ee6e/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L463)):</sup>
You can remove these.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 617 \[r5\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1L61yoE-JNaLKSwj3N)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/5b15ae934d67771acf87eb672908460b6576ee6e/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L617)):</sup>
We'd like to transition to using ObjectEnumerationBuilder.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 644 \[r5\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1L67ods70maiIoLe_I)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/5b15ae934d67771acf87eb672908460b6576ee6e/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L644)):</sup>
Does this work? I think you need to employ the selectors here to get a color per series. Check out linechart.ts: enumerateDataPoints()


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 136 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1Avi8_8AGJOt9hpwET)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/c52901b761b426d0e110278c87d3052c0fc31b19/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L136)):</sup>
Does this data view work now, or still having problems?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by uve** [comment]
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 136 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1Avi8_8AGJOt9hpwET)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/c52901b761b426d0e110278c87d3052c0fc31b19/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L136)):</sup>
Yes, unfortunately it still displays category names instead of series names.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 463 \[r5\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1L5leKKh5RO5V_PH6i)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/5b15ae934d67771acf87eb672908460b6576ee6e/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L463)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 617 \[r5\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1L61yoE-JNaLKSwj3N)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/5b15ae934d67771acf87eb672908460b6576ee6e/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L617)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/areaRangeChart.ts, line 644 \[r5\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1L67ods70maiIoLe_I)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/5b15ae934d67771acf87eb672908460b6576ee6e/src/Clients/Visuals/visuals/samples/areaRangeChart.ts#L644)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 136 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1Avi8_8AGJOt9hpwET)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/c52901b761b426d0e110278c87d3052c0fc31b19/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L136)):</sup>
Ok, the way the metadata should look when you have a series columns (dynamic series) is that you will have column for "lower" and a column for "upper" for each value of the series, and the groupName property on the column should have the value of the series. It looks like none of our sample data actually does this. For now I think just remove the "series" column, you should get one range and no legend.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by jcludwig** [comment]
Reviewed 3 of 4 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Comment by uve** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts, line 136 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124#-K1Avi8_8AGJOt9hpwET)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/c52901b761b426d0e110278c87d3052c0fc31b19/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SimpleAreaRangeData.ts#L136)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/124)

**Pull request merged**
