### PR TITLE
Add a new Tornado Chart.

### PR DESCRIPTION
**Pull request by IgnatVilesov**
[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/123)

### CODE REVIEW

**Comment by v-kazaki** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/tornadoChart.ts, line 812 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K0lrbUhEreUF-srXh2c)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/675819ff2b0b30d67b5f01e18119aca8cc98defa/src/Clients/Visuals/visuals/tornadoChart.ts#L812)):</sup>
Suggest to use minValue = Math.min(d3.min(series[0].values), 0);


---

<sup>**[src/Clients/Visuals/visuals/tornadoChart.ts, line 830 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K0ls5IXJllsndVKENSE)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/675819ff2b0b30d67b5f01e18119aca8cc98defa/src/Clients/Visuals/visuals/tornadoChart.ts#L830)):</sup>
minValues should be used instead of zero


---

<sup>**[src/Clients/Visuals/visuals/tornadoChart.ts, line 932 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K0lsCC9jJKMaSC4Oz6i)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/675819ff2b0b30d67b5f01e18119aca8cc98defa/src/Clients/Visuals/visuals/tornadoChart.ts#L932)):</sup>
private getColumnWidth(value: number, minValue: number, maxValue: number, width: number): number {
   if (minValue == maxValue) {
    return width;
   }
   return width * (value - minValue) / (maxValue - minValue);
}


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123)

**Comment by IgnatVilesov** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/tornadoChart.ts, line 812 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K0lrbUhEreUF-srXh2c)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/675819ff2b0b30d67b5f01e18119aca8cc98defa/src/Clients/Visuals/visuals/tornadoChart.ts#L812)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/tornadoChart.ts, line 830 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K0ls5IXJllsndVKENSE)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/675819ff2b0b30d67b5f01e18119aca8cc98defa/src/Clients/Visuals/visuals/tornadoChart.ts#L830)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/tornadoChart.ts, line 932 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K0lsCC9jJKMaSC4Oz6i)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/675819ff2b0b30d67b5f01e18119aca8cc98defa/src/Clients/Visuals/visuals/tornadoChart.ts#L932)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/tornadoChart.ts, line 258 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K1BG0DzUpVi5pVIpckH)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/163c6e9f45047fdada698f2aba22fd9a162cebde/src/Clients/Visuals/visuals/tornadoChart.ts#L258)):</sup>
This role doesn't exist. I will pull this branch and fix this up for you.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/tornadoChart.ts, line 330 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K1BVq-1hYnHS7ohmBLo)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/163c6e9f45047fdada698f2aba22fd9a162cebde/src/Clients/Visuals/visuals/tornadoChart.ts#L330)):</sup>
Needs to be using our palette colors. Take a look at usage of the ColorHelper type.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123)

**Comment by IgnatVilesov** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[src/Clients/Visuals/visuals/samples/tornadoChart.ts, line 258 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K1BG0DzUpVi5pVIpckH)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/163c6e9f45047fdada698f2aba22fd9a162cebde/src/Clients/Visuals/visuals/samples/tornadoChart.ts#L258)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/samples/tornadoChart.ts, line 330 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123#-K1BVq-1hYnHS7ohmBLo)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/163c6e9f45047fdada698f2aba22fd9a162cebde/src/Clients/Visuals/visuals/samples/tornadoChart.ts#L330)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/123)

**Comment by v-kazaki** [comment]
Looks good.

**Pull request merged**
