### PR TITLE
Word Cloud: 2113 Implement word selection

### PR DESCRIPTION
**Pull request by deniskudelin**
Word Cloud: 2113 Implement word selection

[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/244)

### CODE REVIEW

**Comment by IgnatVilesov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts, line 38 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244#-K7PhZ0167GGvDCn2gqF:-K7PhZ02nzUEar9bBF2l:50618971) ([raw file](https://github.com/microsoft/powerbi-visuals/blob/15458584159768d5bb43e20418cb4f92ee21ca9a/src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts#L38)):*
Please, use spaces instead tabs.

---

*[src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts, line 434 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244#-K7Pld3fwR4XNS0fxDEq:-K7Pld3fwR4XNS0fxDEr:-2052155557) ([raw file](https://github.com/microsoft/powerbi-visuals/blob/bbc4066eb550904a290c90bf307fc2c78214bcaa/src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts#L434)):*
Please, use "getObjectsFromDataView" function.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Comment by IgnatVilesov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts, line 1397 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244#-K7Q5NGkDSzFmLmr0o5g:-K7Q5NGkDSzFmLmr0o5h:-1698887254) ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9143c95b575987f5d66b4f71aaba544a50c8d84f/src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts#L1397)):*
Please, use clearTimeout instead clearInterval.

---

*[src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts, line 1531 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244#-K7Q5GIPGm1YsfuXQ1bH:-K7Q5GIPGm1YsfuXQ1bI:-49688117) ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9143c95b575987f5d66b4f71aaba544a50c8d84f/src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts#L1531)):*
this.updateTimerId ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Comment by deniskudelin** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Comment by deniskudelin** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Comment by deniskudelin** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts, line 434 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244#-K7Pld3fwR4XNS0fxDEq:-K7QAVLFo8wgVQSqM59A:-499146009) ([raw file](https://github.com/microsoft/powerbi-visuals/blob/bbc4066eb550904a290c90bf307fc2c78214bcaa/src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts#L434)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Comment by deniskudelin** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts, line 1397 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244#-K7Q5NGkDSzFmLmr0o5g:-K7QAZkDlGf9HJgkxSti:-499146009) ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9143c95b575987f5d66b4f71aaba544a50c8d84f/src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts#L1397)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Comment by deniskudelin** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts, line 1531 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244#-K7Q5GIPGm1YsfuXQ1bH:-K7QAb2lz3MtKAMrpTQP:-499146009) ([raw file](https://github.com/microsoft/powerbi-visuals/blob/9143c95b575987f5d66b4f71aaba544a50c8d84f/src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts#L1531)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Comment by deniskudelin** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts, line 38 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244#-K7PhZ0167GGvDCn2gqF:-K7QAe81Kms0VW4GidVx:-499146009) ([raw file](https://github.com/microsoft/powerbi-visuals/blob/15458584159768d5bb43e20418cb4f92ee21ca9a/src/Clients/CustomVisuals/visuals/wordCloud/wordCloud.ts#L38)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Comment by IgnatVilesov** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/244)*

**Pull request merged**
