### PR TITLE
Histogram visual

### PR DESCRIPTION
**Pull request by IgnatVilesov**
##### Created a new "Histogram" visual.

[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/118)

### CODE REVIEW

**Comment by MatthLee** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 134 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-sxjgy5PJtbD_Wz95l)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L134)):</sup>
public static capabilities (lower case, necessary for Dev Tools)


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 149 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-sxyEMggZ5n5IQbC14)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L149)):</sup>
where is Y? I think we only need one bucket for the measure. Remove X from dataRoles and leave the dataViewMappings the same
We also need conditions here to make sure the user can only add one measure to the Y bucket, like:
        dataViewMappings: [{
            conditions: [
                { 'Y': { max: 1 }},
            ],
            categorical: ...


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 301 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-t5j1OW4AKrgyHhk-9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L301)):</sup>
nit: don't need the instanceof check


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 306 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-jtdl7X4-SscMpizAs)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L306)):</sup>
nice - thanks for making this a separate function and handling reset-to-default behavior in the property pane


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 346 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-t61KrQgSbv2qTfrKi)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L346)):</sup>
please call these xScale and yScale


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 370 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-jtEpk0FyjlB7bfyFP)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L370)):</sup>
this was just set to default above - combine to one line, move up with the other histogramSettings


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 533 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-t6k6V9Motuu8r_6Ry)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L533)):</sup>
we should be adding tooltipInfo to each data point object so this is easier - see usage of "extend TooltipEnabledDataPoint" in other visuals
this is ok for now, no need to change it, just for future reference.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 624 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-t9g6H9zhFTrc34Rjm)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L624)):</sup>
do we need to use backquotes here? somewhat non-standard


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by MatthLee** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by MatthLee** [comment]
Review status: 8 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 146 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-teQrrAhCKj_NXfgNE)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L146)):</sup>
this isn't working right in the product - we are getting a single aggregate value back, not an array of values to bin. Please test in the product.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by IgnatVilesov** [comment]
Review status: 7 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 134 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-sxjgy5PJtbD_Wz95l)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L134)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 301 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-t5j1OW4AKrgyHhk-9)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L301)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 306 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-jtdl7X4-SscMpizAs)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L306)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 346 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-t61KrQgSbv2qTfrKi)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L346)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 370 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-jtEpk0FyjlB7bfyFP)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L370)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 624 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-t9g6H9zhFTrc34Rjm)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L624)):</sup>

Template Strings (feature of TypeScript 1.4). http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by IgnatVilesov** [comment]
Review status: 1 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 149 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-sxyEMggZ5n5IQbC14)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L149)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 533 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-t6k6V9Motuu8r_6Ry)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L533)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by MatthLee** [comment]
Review status: 1 of 9 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/styles/visuals.less, line 1822 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K03_iT_zn3HHJZAoUxe)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/859c0a243a123fcc74126112d5d1139a7f3a2218/src/Clients/Visuals/styles/visuals.less#L1822)):</sup>
        font-family: @regularFontFamily;
        font-size: 11px;


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by MatthLee** [comment]
Review status: 1 of 9 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/styles/visuals.less, line 1827 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K03_r2bTRewhLFLdv-I)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/859c0a243a123fcc74126112d5d1139a7f3a2218/src/Clients/Visuals/styles/visuals.less#L1827)):</sup>
see other examples of .axisGraphicsContext, e.g.:

    .axisGraphicsContext {
        font-family: @regularFontFamily;
        font-size: 11px;

        text {
            fill: @neutralSecondaryAltColor;
        }

        .axis path, .axis line {
            fill: none;
            stroke: @neutralSecondaryAltColor;
            shape-rendering: crispEdges;
        }
    }


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by MatthLee** [comment]
Review status: 1 of 9 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 149 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-teQrrAhCKj_NXfgNE)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L149)):</sup>
I fixed it, sending you an updated version in email to merge with


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 161 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K03sE4Vgn1ckz_gr0qm)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/859c0a243a123fcc74126112d5d1139a7f3a2218/src/Clients/Visuals/visuals/histogram.ts#L161)):</sup>
please look at other visuals, and how they implement enumerateObject... - this is necessary to expose the options in the property pane.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by MatthLee** [comment]
Reviewed 7 of 8 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 13 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 234 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K05LD_PfaZw-__1eyDM)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/859c0a243a123fcc74126112d5d1139a7f3a2218/src/Clients/Visuals/visuals/histogram.ts#L234)):</sup>
please incorporate the changes I sent via email for tooltip value formatting, axis tick formatting, and color/styles, and push another iteration.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by IgnatVilesov** [comment]
Review status: 5 of 9 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

<sup>**[src/Clients/Visuals/styles/visuals.less, line 1822 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K03_iT_zn3HHJZAoUxe)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/859c0a243a123fcc74126112d5d1139a7f3a2218/src/Clients/Visuals/styles/visuals.less#L1822)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/styles/visuals.less, line 1827 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K03_r2bTRewhLFLdv-I)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/859c0a243a123fcc74126112d5d1139a7f3a2218/src/Clients/Visuals/styles/visuals.less#L1827)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 146 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K-teQrrAhCKj_NXfgNE)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/28b3ba749cd60df01a814fdf7e86fd826053f1b4/src/Clients/Visuals/visuals/histogram.ts#L146)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 161 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K03sE4Vgn1ckz_gr0qm)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/859c0a243a123fcc74126112d5d1139a7f3a2218/src/Clients/Visuals/visuals/histogram.ts#L161)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 234 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K05LD_PfaZw-__1eyDM)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/859c0a243a123fcc74126112d5d1139a7f3a2218/src/Clients/Visuals/visuals/histogram.ts#L234)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by MatthLee** [comment]
Reviewed 2 of 4 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 153 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K0CRAveFJndnvc2gARF)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/0c5e6cb8dc6ce3f84e0d0fbace36512afecf5d1e/src/Clients/Visuals/visuals/histogram.ts#L153)):</sup>
just Grouping, not GroupingOrMeasure


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 159 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K0CRFQ2y02pJEV7V5KN)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/0c5e6cb8dc6ce3f84e0d0fbace36512afecf5d1e/src/Clients/Visuals/visuals/histogram.ts#L159)):</sup>
should probably have a min: 1 also so we don't execute a query until we have a field added


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by IgnatVilesov** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 153 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K0CRAveFJndnvc2gARF)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/0c5e6cb8dc6ce3f84e0d0fbace36512afecf5d1e/src/Clients/Visuals/visuals/histogram.ts#L153)):</sup>
Done.


---

<sup>**[src/Clients/Visuals/visuals/histogram.ts, line 159 \[r4\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118#-K0CRFQ2y02pJEV7V5KN)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/0c5e6cb8dc6ce3f84e0d0fbace36512afecf5d1e/src/Clients/Visuals/visuals/histogram.ts#L159)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Comment by MatthLee** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/118)

**Pull request merged**
