### PR TITLE
Add a new Timeline visual

### PR DESCRIPTION
**Pull request by IgnatVilesov**
[Review on Reviewable](https://reviewable.io/reviews/microsoft/powerbi-visuals/127)

### CODE REVIEW

**Comment by jcludwig** [comment]
<sup>**[src/Clients/PowerBIVisualsTests/helpers/performanceTestsHelpers.ts, line 490 \[r1\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K134lZ0tJPvs7ex8EG6)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/06269d27d6818713da18f3923af98a505105d2de/src/Clients/PowerBIVisualsTests/helpers/performanceTestsHelpers.ts#L490)):</sup>
I'd just leave this out of the perf tests for now.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127)

**Comment by jcludwig** [comment]
Please integrate Cong's latest changes, then I will take another look.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 887 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1GwcOL5ivAB9iPFPh-)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/e4fd726bfe887f0a90573720b025c98f9d96e191/src/Clients/Visuals/visuals/timeline.ts#L887)):</sup>
We can't go outside the visual like this. There is no way to enforce a minimum width, please remove this.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127)

**Comment by vtkalek** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 887 \[r2\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1GwcOL5ivAB9iPFPh-)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/e4fd726bfe887f0a90573720b025c98f9d96e191/src/Clients/Visuals/visuals/timeline.ts#L887)):</sup>
I removed it - Done


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 738 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1LCff-J35OFqDQ4zqy)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/003cad06d8bd1a9ab7ad091d5331ef0519dc4320/src/Clients/Visuals/visuals/timeline.ts#L738)):</sup>
Should be using DataViewObject.getValue() for these.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127)

**Comment by jcludwig** [comment]
Reviewed 7 of 9 files at r1, 1 of 1 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 161 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1LBflzFI68MAZa6HGJ)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/003cad06d8bd1a9ab7ad091d5331ef0519dc4320/src/Clients/Visuals/visuals/timeline.ts#L161)):</sup>
Prefer "== null"


---

<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 232 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1LDAPxaQ4lf8GoQJyw)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/003cad06d8bd1a9ab7ad091d5331ef0519dc4320/src/Clients/Visuals/visuals/timeline.ts#L232)):</sup>
This is not the newest filter code.


---

<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 445 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1LBvscV5zpH9QSiAFR)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/003cad06d8bd1a9ab7ad091d5331ef0519dc4320/src/Clients/Visuals/visuals/timeline.ts#L445)):</sup>
Uh oh, do we need this? Can you elaborate on the need for this if so?


---

<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 510 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1LC3LKupT11S1j9qPM)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/003cad06d8bd1a9ab7ad091d5331ef0519dc4320/src/Clients/Visuals/visuals/timeline.ts#L510)):</sup>
Can't do this. You should just be able to do this with .sprite() call in the less file.


---

<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 1132 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1LD4tlNyQzYVokPLef)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/003cad06d8bd1a9ab7ad091d5331ef0519dc4320/src/Clients/Visuals/visuals/timeline.ts#L1132)):</sup>
Please use ObjectEnumerationBuilder.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127)

**Comment by jcludwig** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127)

**Comment by jcludwig** [comment]
<sup>**[src/Clients/Visuals/visuals/timeline.ts, line 510 \[r3\]](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127#-K1LC3LKupT11S1j9qPM)** ([raw file](https://github.com/microsoft/powerbi-visuals/blob/003cad06d8bd1a9ab7ad091d5331ef0519dc4320/src/Clients/Visuals/visuals/timeline.ts#L510)):</sup>
Actually, let's change this to a base64 encoded image (https://css-tricks.com/data-uris/)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/powerbi-visuals/127)

**Comment by sgrebnov** [comment]
This PR seems to be broken and contains unrelated changes, closing.... @IgnatVilesov feel free to send another one  if required

**Pull request closed without merging**
