### PR TITLE
Changed the instructions for creating self-signed certificates

### PR DESCRIPTION
**Pull request by aschuhardt**
See issue #550 

Attempting to run `pbiviz --create-cert` results in an error message.

The correct instruction is to run `pbiviz --install-cert`.

I want to correct this so that others don't trip over it like I did.

### CODE REVIEW

**Comment by zidhuss** [comment]
Came across the same issue. Is there a reason why this hasn't been merged in yet?

**Comment by zBritva** [comment]
Docs here are outdated. Repo will be closed soon.

**Comment by aschuhardt** [comment]
> Docs here are outdated. Repo will be closed soon.

Where are up-to-date docs?

**Comment by zBritva** [comment]
@aschuhardt docs are moving into https://docs.microsoft.com/power-bi/power-bi-custom-visuals
Part of docs will published soon

**Pull request closed without merging**
