### PR TITLE
Timeline issues: 2383, 2417, 2413, 2414, 2416, 2418

### PR DESCRIPTION
**Pull request by tomsoir**

### CODE REVIEW

**Comment by tomsoir** [comment]
DON"T MERGE IT, please. :)

**Comment by sgrebnov** [comment]
@tomsoir please start commits using visual name + squash before merge

**Comment by tomsoir** [comment]
@sgrebnov  Squashed and renamed.

**Comment by sgrebnov** [comment]
:+1: merged!

**Pull request merged**
